server:
  port: 9527
spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: zuul-gateway:9527
    prefer-ip-address: true


zuul:
  routes:
    ordersystem.serviceId: service-provider
    ordersystem.path: /menuprovider/**
  #  ignored-services: microservicecloud-dept #针对于单个微服务
  ignored-services: "*"
  prefix: /yaolong


